import express from 'express';
import { z } from 'zod';
import { authenticateToken } from '../middleware/auth.middleware.js';
import { validate } from '../middleware/validate.middleware.js';
import { uuid,pagination } from '../validation/common.schemas.js';
import * as controller from '../controllers/affinity.controller.js';
const router=express.Router();
const id=validate({params:z.object({id:uuid})});
router.use(authenticateToken());
router.post('/activity',controller.recordActivity);
router.get('/',controller.getRecommendations);
router.put('/preferences',validate({body:z.object({enabled:z.boolean()})}),controller.setPreferences);
router.get('/likes',validate({query:pagination}),controller.getAffinityLikes);
router.post('/likes/:id/return',id,controller.plusOnly,controller.returnAffinityLike);
router.get('/requests',validate({query:pagination}),controller.getRequests);
router.post('/requests/:id/accept',id,controller.acceptConversation);
router.post('/requests/:id/reject',id,controller.rejectConversation);
router.post('/recommendations/:id/dismiss',id,controller.dismissRecommendation);
router.post('/recommendations/:id/like',id,controller.plusOnly,controller.likeRecommendation);
router.post('/recommendations/:id/request',id,controller.plusOnly,validate({body:z.object({clientId:uuid,text:z.string().trim().min(1).max(4000)})}),controller.requestConversation);
router.post('/blocks/:id',id,controller.blockUser);
router.get('/contact/:id',id,controller.getContactStatus);
export default router;
