const UPLOAD_DIR_STRING = 'assets';
const UPLOAD_DIR_IMG_STRING = UPLOAD_DIR_STRING + '/img';
const UPLOAD_DIR_PROFILES_STRING = UPLOAD_DIR_IMG_STRING + '/profiles';
const DEFAULT_AVATAR_URL = `${UPLOAD_DIR_PROFILES_STRING}/Goku.webp`;

export { UPLOAD_DIR_STRING, UPLOAD_DIR_IMG_STRING, UPLOAD_DIR_PROFILES_STRING, DEFAULT_AVATAR_URL };
