export const seedUsers = [
            {
                id: '11111111-1111-4111-8111-111111111111',
                username: 'kirito',
                email: 'kirito@example.com',
                password: 'PasswordSegura123!',
                phoneNumber: '+34611111222',
                authProvider: 'email',
                isVerified: true,
                bio: 'Espadachin negro en busca de party para coop y aventuras.',
                gender: 'male',
                birthdate: '1997-07-10',
                residenceCity: 'Palma',
                residenceRegion: 'Islas Baleares',
                residenceCountryCode: 'ES',
                residenceLatitude: 39.5696,
                residenceLongitude: 2.6502,
                currentLatitude: 39.5696,
                currentLongitude: 2.6502,
                animes: ['Sword Art Online', 'Frieren: Beyond Journey\'s End'],
                games: ['The Legend of Zelda: Tears of the Kingdom', 'Elden Ring'],
                relationshipGoals: ['relationship', 'friends'],
                spokenLanguages: ['es', 'en'],
                prompts: [
                    { code: 'party_role', answer: 'DPS solitario que aprende a confiar en su party.' },
                    { code: 'favorite_videogame', answer: 'Sword Art Online (o cualquier MMORPG inmersivo).' }
                ],
            },
            {
                id: '22222222-2222-4222-8222-222222222222',
                username: 'asuna',
                email: 'asuna@example.com',
                password: 'PasswordSegura123!',
                phoneNumber: '+34633334444',
                authProvider: 'google',
                isVerified: true,
                bio: 'Destello veloz y cocinera experta en juegos de rol.',
                gender: 'female',
                birthdate: '1998-03-15',
                residenceCity: 'Inca',
                residenceRegion: 'Islas Baleares',
                residenceCountryCode: 'ES',
                residenceLatitude: 39.7211,
                residenceLongitude: 2.9110,
                currentLatitude: 39.7211,
                currentLongitude: 2.9110,
                animes: ['Kaguya-sama: Love is War', 'Haikyuu!!'],
                games: ['Genshin Impact', 'Animal Crossing: New Horizons'],
                relationshipGoals: ['relationship', 'marriage'],
                spokenLanguages: ['es', 'en', 'ja'],
                prompts: [
                    { code: 'party_role', answer: 'Sub-líder veloz y healer de apoyo cuando hace falta.' },
                    { code: 'comfort_anime', answer: 'Kaguya-sama y Frieren.' }
                ],
            },
            {
                id: '12121212-1212-4212-8212-121212121212',
                username: 'lina_palma',
                email: 'lina.palma@example.com',
                password: 'PasswordSegura123!',
                phoneNumber: '+34611223344',
                authProvider: 'email',
                isVerified: true,
                bio: 'Amante del cosplay y el café cerca de la bahía de Palma. ¿Hacemos maratón de anime o una sesión de fotos?',
                gender: 'female',
                birthdate: '2001-05-14',
                residenceCity: 'Palma',
                residenceRegion: 'Islas Baleares',
                residenceCountryCode: 'ES',
                residenceLatitude: 39.5710,
                residenceLongitude: 2.6480,
                currentLatitude: 39.5710,
                currentLongitude: 2.6480,
                animes: ['Jujutsu Kaisen', 'Chainsaw Man', 'Attack on Titan'],
                games: ['Genshin Impact', 'VALORANT'],
                relationshipGoals: ['friends', 'relationship', 'casual'],
                spokenLanguages: ['es', 'en'],
                prompts: [
                    { code: 'comfort_anime', answer: 'Jujutsu Kaisen y Demon Slayer.' },
                    { code: 'unpopular_opinion', answer: 'El manga siempre tiene un ritmo mejor que los rellenos de temporada.' }
                ],
            },
            {
                id: '13131313-1313-4313-8313-131313131313',
                username: 'rafa_manacor',
                email: 'rafa.manacor@example.com',
                password: 'PasswordSegura123!',
                phoneNumber: '+34622334455',
                authProvider: 'email',
                isVerified: true,
                bio: 'Gamer en Mallorca. Buscando duo para rankeds en shooters o pasar tardes de coop chill.',
                gender: 'male',
                birthdate: '1999-11-20',
                residenceCity: 'Marratxí',
                residenceRegion: 'Islas Baleares',
                residenceCountryCode: 'ES',
                residenceLatitude: 39.6420,
                residenceLongitude: 2.7210,
                currentLatitude: 39.6420,
                currentLongitude: 2.7210,
                animes: ['One Punch Man', 'Mob Psycho 100', 'Vinland Saga', 'Sword Art Online'],
                games: ['Counter-Strike 2', 'Elden Ring', 'League of Legends'],
                relationshipGoals: ['casual', 'friends', 'relationship'],
                spokenLanguages: ['es', 'en'],
                prompts: [
                    { code: 'favorite_videogame', answer: 'Elden Ring y la saga Dark Souls.' },
                    { code: 'party_role', answer: 'Tank de primera linea aguantando los golpes.' }
                ],
            },
            {
                id: '24242424-2424-4424-8424-242424242424',
                username: 'antoine_toulouse',
                email: 'antoine.toulouse@example.com',
                password: 'PasswordSegura123!',
                phoneNumber: '+33655443322',
                authProvider: 'email',
                isVerified: true,
                bio: 'De Toulouse, fan de RPGs fantastiques et marathons animés. Cherche des amis et du coop !',
                gender: 'male',
                birthdate: '1998-08-12',
                residenceCity: 'Toulouse',
                residenceRegion: 'Occitanie',
                residenceCountryCode: 'FR',
                residenceLatitude: 43.6047,
                residenceLongitude: 1.4442,
                currentLatitude: 43.6047,
                currentLongitude: 1.4442,
                animes: ['Fullmetal Alchemist: Brotherhood', 'Death Note', 'Steins;Gate'],
                games: ['The Witcher 3: Wild Hunt', 'Baldur\'s Gate 3', 'Final Fantasy XIV Online'],
                relationshipGoals: ['relationship', 'friends'],
                spokenLanguages: ['fr', 'en', 'es'],
                prompts: [
                    { code: 'favorite_videogame', answer: 'Baldur\'s Gate 3 et The Witcher 3.' },
                    { code: 'party_role', answer: 'Mage support ou soigneur tactique.' }
                ],
            },
            {
                id: '25252525-2525-4525-8525-252525252525',
                username: 'lea_toulouse',
                email: 'lea.toulouse@example.com',
                password: 'PasswordSegura123!',
                phoneNumber: '+33677889900',
                authProvider: 'email',
                isVerified: true,
                bio: 'Cosplayeuse et fan de jeux chill à Toulouse. Partante pour des soirées jeux de société ou convention !',
                gender: 'female',
                birthdate: '2001-02-28',
                residenceCity: 'Toulouse',
                residenceRegion: 'Occitanie',
                residenceCountryCode: 'FR',
                residenceLatitude: 43.6047,
                residenceLongitude: 1.4442,
                currentLatitude: 43.6047,
                currentLongitude: 1.4442,
                animes: ['Violet Evergarden', 'Demon Slayer: Kimetsu no Yaiba', 'Spy x Family'],
                games: ['Animal Crossing: New Horizons', 'Genshin Impact', 'Stardew Valley'],
                relationshipGoals: ['friends', 'casual'],
                spokenLanguages: ['fr', 'en'],
                prompts: [
                    { code: 'comfort_anime', answer: 'Violet Evergarden et Spy x Family.' },
                    { code: 'dream_job', answer: 'Créatrice d\'accessoires cosplay et artiste 3D.' }
                ],
            },
            {
                id: '33333333-3333-4333-8333-333333333333',
                username: 'feryael',
                email: 'test@mirailink.xyz',
                password: 'PasswordSegura123!',
                phoneNumber: '+34655556666',
                authProvider: 'email',
                isVerified: true,
                bio: 'Testing MiraiLink user.',
                gender: 'male',
                birthdate: '1999-01-01',
                residenceCity: 'Madrid',
                residenceRegion: 'Madrid',
                residenceCountryCode: 'ES',
                residenceLatitude: 40.4168,
                residenceLongitude: -3.7038,
                currentLatitude: 40.4168,
                currentLongitude: -3.7038,
                animes: ['Jujutsu Kaisen', 'Chainsaw Man'],
                games: ['VALORANT', 'Stardew Valley'],
                relationshipGoals: ['friends', 'relationship'],
                spokenLanguages: ['es', 'en'],
                prompts: [
                    { code: 'favorite_videogame', answer: 'VALORANT y juegos cooperativos indie.' }
                ],
            },
            {
                id: '44444444-4444-4444-8444-444444444444',
                username: 'nora_barcelona',
                email: 'nora.barcelona@example.com',
                password: 'PasswordSegura123!',
                phoneNumber: '+34677778888',
                authProvider: 'email',
                isVerified: true,
                bio: 'Cosplay, manga clásico y cafeterías frikis. Siempre buscando una buena charla sobre historias que dejan huella.',
                gender: 'female',
                birthdate: '2001-04-10',
                residenceCity: 'Barcelona',
                residenceRegion: 'Cataluña',
                residenceCountryCode: 'ES',
                residenceLatitude: 41.3874,
                residenceLongitude: 2.1686,
                currentLatitude: 41.3874,
                currentLongitude: 2.1686,
                animes: ['Frieren: Beyond Journey\'s End', 'Steins;Gate'],
                games: ['Persona 5 Royal'],
                relationshipGoals: ['relationship', 'friends'],
                spokenLanguages: ['es', 'en'],
                prompts: [
                    { code: 'comfort_anime', answer: 'Frieren: Beyond Journey\'s End.' }
                ],
            },
            {
                id: '55555555-5555-4555-8555-555555555555',
                username: 'marc_valencia',
                email: 'marc.valencia@example.com',
                password: 'PasswordSegura123!',
                phoneNumber: '+34688889999',
                authProvider: 'email',
                isVerified: true,
                bio: 'Desarrollo juegos indie, dibujo pixel art y me pierdo con gusto en un buen RPG cooperativo.',
                gender: 'male',
                birthdate: '1998-09-21',
                residenceCity: 'Valencia',
                residenceRegion: 'Comunidad Valenciana',
                residenceCountryCode: 'ES',
                residenceLatitude: 39.4699,
                residenceLongitude: -0.3763,
                currentLatitude: 39.4699,
                currentLongitude: -0.3763,
                animes: ['Psycho-Pass', 'Fullmetal Alchemist: Brotherhood'],
                games: ['Monster Hunter: World', 'The Legend of Zelda: Tears of the Kingdom'],
                relationshipGoals: ['friends', 'casual'],
                spokenLanguages: ['es', 'en'],
                prompts: [
                    { code: 'party_role', answer: 'Creador de mapas y soporte técnico del equipo.' }
                ],
            },
            {
                id: '66666666-6666-4666-8666-666666666666',
                username: 'claire_paris',
                email: 'claire.paris@example.com',
                password: 'PasswordSegura123!',
                phoneNumber: '+33611112222',
                authProvider: 'email',
                isVerified: true,
                bio: 'Estudio japonés, colecciono figuras y disfruto los RPG narrativos y las películas de animación.',
                gender: 'female',
                birthdate: '2002-07-09',
                residenceCity: 'París',
                residenceRegion: 'Île-de-France',
                residenceCountryCode: 'FR',
                residenceLatitude: 48.8566,
                residenceLongitude: 2.3522,
                currentLatitude: 48.8566,
                currentLongitude: 2.3522,
                animes: ['Violet Evergarden', 'Samurai Champloo'],
                games: ['Final Fantasy XIV Online'],
                relationshipGoals: ['relationship', 'friends'],
                spokenLanguages: ['fr', 'ja', 'en'],
                prompts: [
                    { code: 'comfort_anime', answer: 'Violet Evergarden.' }
                ],
            },
            {
                id: '77777777-7777-4777-8777-777777777777',
                username: 'yuki_tokyo',
                email: 'yuki.tokyo@example.com',
                password: 'PasswordSegura123!',
                phoneNumber: '+819011112222',
                authProvider: 'email',
                isVerified: true,
                bio: 'Ilustración digital, Studio Ghibli y ramen. Me encantan las conversaciones tranquilas sobre mundos imaginarios.',
                gender: 'female',
                birthdate: '2000-01-18',
                residenceCity: 'Tokio',
                residenceRegion: 'Kanto',
                residenceCountryCode: 'JP',
                residenceLatitude: 35.6762,
                residenceLongitude: 139.6503,
                currentLatitude: 35.6762,
                currentLongitude: 139.6503,
                animes: ['One Piece', 'Haikyuu!!'],
                games: ['Pokémon GO', 'Animal Crossing: New Horizons'],
                relationshipGoals: ['friends', 'relationship'],
                spokenLanguages: ['ja', 'en'],
                prompts: [
                    { code: 'comfort_anime', answer: 'Películas de Studio Ghibli y Haikyuu!!.' }
                ],
            },
            {
                id: '88888888-8888-4888-8888-888888888888',
                username: 'isha_mumbai',
                email: 'isha.mumbai@example.com',
                password: 'PasswordSegura123!',
                phoneNumber: '+919811112222',
                authProvider: 'email',
                isVerified: true,
                bio: 'Product designer, fan de One Piece y Stardew Valley. Me encantan las conversaciones que empiezan hablando de anime y terminan hablando de todo.',
                gender: 'female',
                birthdate: '1999-04-22',
                residenceCity: 'Mumbai',
                residenceRegion: 'Maharashtra',
                residenceCountryCode: 'IN',
                residenceLatitude: 19.0760,
                residenceLongitude: 72.8777,
                currentLatitude: 19.0760,
                currentLongitude: 72.8777,
                animes: ['One Piece', 'Haikyuu!!'],
                games: ['Stardew Valley', 'The Sims 4'],
                relationshipGoals: ['friends'],
                spokenLanguages: ['en'],
                prompts: [
                    { code: 'favorite_videogame', answer: 'Stardew Valley por su paz y comunidad.' }
                ],
            },
            {
                id: '99999999-9999-4999-8999-999999999999',
                username: 'leo_newyork',
                email: 'leo.newyork@example.com',
                password: 'PasswordSegura123!',
                phoneNumber: '+12125551234',
                authProvider: 'email',
                isVerified: true,
                bio: 'Fotografía, cómics y speedruns de indies. Busco recomendaciones de roguelikes y bandas sonoras épicas.',
                gender: 'male',
                birthdate: '2001-12-03',
                residenceCity: 'Nueva York',
                residenceRegion: 'New York',
                residenceCountryCode: 'US',
                residenceLatitude: 40.7128,
                residenceLongitude: -74.0060,
                currentLatitude: 40.7128,
                currentLongitude: -74.0060,
                animes: ['Mob Psycho 100', 'Cowboy Bebop'],
                games: ['Stardew Valley', 'Genshin Impact'],
                relationshipGoals: ['casual', 'friends'],
                spokenLanguages: ['en', 'es'],
                prompts: [
                    { code: 'favorite_videogame', answer: 'Hades y Celeste.' }
                ],
            },
        ];
